### ISSUE TITLE
Cannot close file correctly

### ISSUE THREAD

**Issue by zhouchong90** [GoogleChromeLabs/text-app#259]
When I open a lot of files like 20 txt, then I cannot close them correctly. They'll just looped and appear again and again. Also, we need a close all function!

**Comment by beaufortfrancois** [comment]
Hello BIMDataHub Team,

I've just opened more that 20 files with the Text App and and I cannot reproduce the issue. Please let me know how all the steps to end in this situation.

Regarding the close all function, you might want to file a separate issue so that we can track how many users would find this useful.

**Comment by BugsNash** [comment]
Closing as can't reproduce
