### ISSUE TITLE
Edit Android Files on ChromeOS

### ISSUE THREAD

**Issue by jonathanlb** [GoogleChromeLabs/text-app#332]
Is it possible to edit files accessible to the Android emulator in ChromeOS?  I'd like to be able to edit files used under Termux, but text-app does not allow file navigation outside of a narrow set of directories.  Turbo Editor can access a wider range of files once one enables the Storage-access-framework option (though Turbo Editor is also an Android app).

**Comment by BugsNash** [comment]
Hi jonathanlb

This issue is not controlled by the Text app but by Chrome OS. Currently Android files are not accessible through Chrome OS, however Android apps that have been given permission may access Chrome OS files.

The way to do this in Termux is to run termux-setup-storage (you will need to grant termux permission to access files). After that termux emulates the Chrome OS filesystem in the storage directory. Save (or move) files there to share with the text app.

Hope that helps!

**Comment by jonathanlb** [comment]
Thanks, BugsNash.  The only local directories that appear to the Text app file chooser are Download and the external SD card.  Is it possible to locate others with Text app?

(Even after running termux-setup-storage, Termux doesn't have full access to the ChromeOS shared filesystem -- e.g. chmod fails -- hence the inquiry to allow Text app to edit the Android files.... oh, well.)

**Comment by BugsNash** [comment]
Text app can only access what Chrome OS filesystem allows, which at the moment does not allow Android files. Currently you can access Downloads, Google Drive, Pictures, Music, etc. For a file that needs permission changes you might want to write a script for moving it and chmod'ing it back and forth (unfortunately).

**Comment by jonathanlb** [comment]
Sorry, I don't think I was clear.  How can I create a local directory not under Download or SD Card that Text app can access?  The only local directories under the Text app file chooser root are Download and SD Card.  (Or does Chrome OS not allow new top-level user directories?)

**Comment by BugsNash** [comment]
It seems not? https://productforums.google.com/forum/#!topic/chromebook-central/Jsl-NhKmyPs

If you're going to be working with lots of files that you don't want to lose it's probably best to store them on Google Drive instead of on the local file system (which you should be able to access through the Files app, which the Text app uses for opening and saving files.
