### ISSUE TITLE
How to open text app?

### ISSUE THREAD

**Issue by reinkefj** [GoogleChromeLabs/text-app#508]
Maybe a "dumb question" but after TEXT app is installed, how does one start it?

Be gentle; I'm old and maybe ready for the home.  

(I really think I'm a smart fat old white guy injineer!)

**Comment by zainafzal08** [comment]
Hey reinkefj! Thanks for writing in :D

Assuming you are on a chrome os device, you can open it by finding it in the app drawer, either swipe up from the bottom of the screen if you have a touch screen or click on the circular button on the bottom left of the screen:

![Screenshot 2020-05-18 at 07 35 24 - Display 1 (1)](https://user-images.githubusercontent.com/12245732/82160661-453adf00-98da-11ea-9ab7-7b27a86c7e3d.png)

Then you can scroll or swipe through the pages until you find it. Also if you have a text file you want to open in the text app you can find it in the files app, click on the file once to select it, then from the top right click on open to show a dropdown, then click on text:

![Screenshot 2020-05-18 at 07 36 57 - Display 2](https://user-images.githubusercontent.com/12245732/82160691-6f8c9c80-98da-11ea-9967-3ee7f33e4720.png)

If you are not on a chromeos device you sadly might have some trouble because chrome apps are being deprecated, in that case i'd suggest finding the equivalent text app for your operating system (notepad on windows or TextEdit for mac) or if you'd like something online google keep or google docs may be helpful :)

Hope this helps!

**Comment by reinkefj** [comment]
got it. thanks.  Had a case of the dumbs.

# - # - # - # - #
“Reality is that which when we stop believing in it doesn’t go away.” —
Philip K. Dick
