### ISSUE TITLE
Shortcut to Duplicate Line

### ISSUE THREAD

**Issue by alkiman** [GoogleChromeLabs/text-app#562]
Could you add a shortcut key to duplicate the line at the current cursor position?
For example as a    ctrl-d
I do it often and currently one can simulate it in 4 steps as:
select line   ctrl-c   ctrl-v   ctrl-v

**Comment by ZufengW** [comment]
Since v0.8 Text app uses CodeMirror 6's default keymap. [Keyboard shortcuts](https://codemirror.net/docs/ref/#commands.defaultKeymap) include:
 * Shift-Alt-ArrowUp: [copyLineUp](https://codemirror.net/docs/ref/#commands.copyLineUp)
 * Shift-Alt-ArrowDown: [copyLineDown](https://codemirror.net/docs/ref/#commands.copyLineDown)
